spring.application.name=pdp-online
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/pdponline
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


jwt.token.ttl=86400000
jwt.secretkey=SFERAACADEMYKEY

supabase.url=https://lrfpjdwgvepspexxwgiy.storage.supabase.co
supabase.api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZnBqZHdndmVwc3BleHh3Z2l5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDUxMDM5OCwiZXhwIjoyMDkwMDg2Mzk4fQ.slE8g-wKy9rtN98NTkXA4i8k-9OSdvzsr1iufC_EQmo
supabase.bucket_name=media

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


server.tomcat.connection-timeout=3s
security.whitelist =/auth/**,/swagger-ui/**,/swagger-ui.html,/v2/api-docs,/v3/api-docs,\
  /v3/api-docs/swagger-config,/swagger-resources/**,/webjars/**,/ws/**,/index.html,/




# ========== REDIS SOZLAMALARI (qo'shiladi) ==========
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Parol yo'q bo'lsa quyidagi qatorni qo'shmang
# spring.data.redis.password=yourpassword

# Connection pool sozlamalari
#spring.data.redis.lettuce.pool.max-active=10
#spring.data.redis.lettuce.pool.max-idle=5
#spring.data.redis.lettuce.pool.min-idle=1